import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <a href="#main-content" className="skip-to-content absolute left-2 top-2 z-50 bg-black text-white px-4 py-2 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 transition-transform -translate-y-16 focus:translate-y-0" tabIndex={0}>
          Skip to main content
        </a>
        {children}
      </body>
    </html>
  );
}
